[
    {
        _id: ObjectId("635fec0e67862114b5a6a83b"),
        authorChannelId: { value: 'UCEP0baLqzqUUZ1v3LhGjgjw' },
        authorChannelUrl: 'http://www.youtube.com/channel/UCEP0baLqzqUUZ1v3LhGjgjw',
        authorDisplayName: 'arun Samala',
        authorProfileImageUrl: 'https://yt3.ggpht.com/ytc/AMLnZu-vBdQqScOVwQeLOc7ZmeJUj9_xqakFtWGDIgBmny4=s48-c-k-c0x00ffffff-no-rj',
        canRate: true,
        likeCount: 0,
        publishedAt: '2022-10-29T04:53:41.000Z',
        textDisplay: '<a href="https://www.youtube.com/watch?v=Jo0D_u-QSXs&amp;t=2m50s">2:50</a>',
        textOriginal: '2:50',
        updatedAt: '2022-10-29T04:53:41.000Z',
        videoId: 'Jo0D_u-QSXs',
        viewerRating: 'none'
    },
    {
        _id: ObjectId("635fec0e67862114b5a6a83c"),
        authorChannelId: { value: 'UCeO0Y1PbZaaSB1-KGLowuew' },
        authorChannelUrl: 'http://www.youtube.com/channel/UCeO0Y1PbZaaSB1-KGLowuew',
        authorDisplayName: 'Taraka Surendra Balla',
        authorProfileImageUrl: 'https://yt3.ggpht.com/mNaytUFgALHxFwPpEq7_YStDJioY68rjjpqHPEdRoTkFKY8Dlt1pvsQ6Iymt3U-hukZ_1YU0=s48-c-k-c0x00ffffff-no-rj',
        canRate: true,
        likeCount: 0,
        publishedAt: '2022-10-28T14:45:11.000Z',
        textDisplay: 'ట్రావెలింగ్ అంటే పిచ్చి ఉన్నవారు.. (నాలానే)<br>ఒక లైక్ చెయ్యండి',
        textOriginal: 'ట్రావెలింగ్ అంటే పిచ్చి ఉన్నవారు.. (నాలానే)\nఒక లైక్ చెయ్యండి',
        updatedAt: '2022-10-28T14:45:11.000Z',
        videoId: 'Jo0D_u-QSXs',
        viewerRating: 'none'
    },
    {
        _id: ObjectId("635fec0e67862114b5a6a83d"),
        authorChannelId: { value: 'UCeO0Y1PbZaaSB1-KGLowuew' },
        authorChannelUrl: 'http://www.youtube.com/channel/UCeO0Y1PbZaaSB1-KGLowuew',
        authorDisplayName: 'Taraka Surendra Balla',
        authorProfileImageUrl: 'https://yt3.ggpht.com/mNaytUFgALHxFwPpEq7_YStDJioY68rjjpqHPEdRoTkFKY8Dlt1pvsQ6Iymt3U-hukZ_1YU0=s48-c-k-c0x00ffffff-no-rj',
        canRate: true,
        likeCount: 0,
        publishedAt: '2022-10-28T14:42:49.000Z',
        textDisplay: 'My dream ride <br>Andra to Leh-ladakh',
        textOriginal: 'My dream ride \nAndra to Leh-ladakh',
        updatedAt: '2022-10-28T14:42:49.000Z',
        videoId: 'Jo0D_u-QSXs',
        viewerRating: 'none'
    },
    {
        _id: ObjectId("635fec0e67862114b5a6a83e"),
        authorChannelId: { value: 'UCh-mCoouKvO0pSHVB-eIPCQ' },
        authorChannelUrl: 'http://www.youtube.com/channel/UCh-mCoouKvO0pSHVB-eIPCQ',
        authorDisplayName: 'Lucky Gaming',
        authorProfileImageUrl: 'https://yt3.ggpht.com/BQJe9aOEoKa_U-aVTd0TggX_MP2fslzS26IKYjwhw9KZnDQuSZpYKSFyd7MpX4SCJ3Iuv1HpLNo=s48-c-k-c0x00ffffff-no-rj',
        canRate: true,
        likeCount: 0,
        publishedAt: '2022-10-27T18:30:07.000Z',
        textDisplay: 'Day 53 listiling this song',
        textOriginal: 'Day 53 listiling this song',
        updatedAt: '2022-10-27T18:30:07.000Z',
        videoId: 'Jo0D_u-QSXs',
        viewerRating: 'none'
    },
    {
        _id: ObjectId("635fec0e67862114b5a6a83f"),
        authorChannelId: { value: 'UCDQAbfhCpN5LfAvIjXXQaGA' },
        authorChannelUrl: 'http://www.youtube.com/channel/UCDQAbfhCpN5LfAvIjXXQaGA',
        authorDisplayName: 'Bontha kumari Kumari',
        authorProfileImageUrl: 'https://yt3.ggpht.com/ytc/AMLnZu9nWPfrPK6iu_t5x0yNOCslkUSm49BjB8kacXy-I1Va0Ww1T_I4e6ZevLxdtv-N=s48-c-k-c0x00ffffff-no-rj',
        canRate: true,
        likeCount: 0,
        publishedAt: '2022-10-26T08:18:26.000Z',
        textDisplay: 'One of my favourite song 😔😔',
        textOriginal: 'One of my favourite song 😔😔',
        updatedAt: '2022-10-26T08:18:26.000Z',
        videoId: 'Jo0D_u-QSXs',
        viewerRating: 'none'
    },
    {
        _id: ObjectId("635fec0e67862114b5a6a840"),
        authorChannelId: { value: 'UCJGdF2EpRH8KxJcurAYFlUw' },
        authorChannelUrl: 'http://www.youtube.com/channel/UCJGdF2EpRH8KxJcurAYFlUw',
        authorDisplayName: 'Vootla Ashanjali',
        authorProfileImageUrl: 'https://yt3.ggpht.com/ytc/AMLnZu-qdXsyBfSfbu0F2d-p47h5xHENWvQpl575wmt7puj8RwZah6K6vv3CEwk2T042=s48-c-k-c0x00ffffff-no-rj',
        canRate: true,
        likeCount: 0,
        publishedAt: '2022-10-19T13:30:36.000Z',
        textDisplay: 'Klm klik M ina know know know know know k',
        textOriginal: 'Klm klik M ina know know know know know k',
        updatedAt: '2022-10-19T13:30:36.000Z',
        videoId: 'Jo0D_u-QSXs',
        viewerRating: 'none'
    },
    {
        _id: ObjectId("635fec0e67862114b5a6a841"),
        authorChannelId: { value: 'UCGmNzhO-nBw3iu4qKMvd2Dg' },
        authorChannelUrl: 'http://www.youtube.com/channel/UCGmNzhO-nBw3iu4qKMvd2Dg',
        authorDisplayName: 'Jai Maloth',
        authorProfileImageUrl: 'https://yt3.ggpht.com/ytc/AMLnZu9gfDbjJkSj_Oslto6F6M1vI-QBEo8TWkS0GE7vVg=s48-c-k-c0x00ffffff-no-rj',
        canRate: true,
        likeCount: 0,
        publishedAt: '2022-10-18T17:15:16.000Z',
        textDisplay: 'I love this song',
        textOriginal: 'I love this song',
        updatedAt: '2022-10-18T17:15:16.000Z',
        videoId: 'Jo0D_u-QSXs',
        viewerRating: 'none'
    },
    {
        _id: ObjectId("635fec0e67862114b5a6a842"),
        authorChannelId: { value: 'UCC3Guoz_7EAO9grDVNBxg4w' },
        authorChannelUrl: 'http://www.youtube.com/channel/UCC3Guoz_7EAO9grDVNBxg4w',
        authorDisplayName: 'NTR the GOD 💥',
        authorProfileImageUrl: 'https://yt3.ggpht.com/UsH2sJh7us_pxeIVgR2KRQ1Gmzf3DR28LeH8y1-9vl7fyDH0afNoX4Zds4DZg7YMFV8x_FOBUw=s48-c-k-c0x00ffffff-no-rj',
        canRate: true,
        likeCount: 1,
        publishedAt: '2022-10-13T14:14:40.000Z',
        textDisplay: 'Anybody in 2022 ✋',
        textOriginal: 'Anybody in 2022 ✋',
        updatedAt: '2022-10-13T14:14:40.000Z',
        videoId: 'Jo0D_u-QSXs',
        viewerRating: 'none'
    },
    {
        _id: ObjectId("635fec0e67862114b5a6a843"),
        authorChannelId: { value: 'UCAANhAt_N9p_I7tB2aUkv8w' },
        authorChannelUrl: 'http://www.youtube.com/channel/UCAANhAt_N9p_I7tB2aUkv8w',
        authorDisplayName: 'AJAY RAO',
        authorProfileImageUrl: 'https://yt3.ggpht.com/eHQBoAiYk0HWAtP5kmkb1CysasjEPqqLjNzWjb5agEkeFrMha_TBJaOniCo7oncu2Wg30KM3fA=s48-c-k-c0x00ffffff-no-rj',
        canRate: true,
        likeCount: 0,
        publishedAt: '2022-10-11T05:18:28.000Z',
        textDisplay: 'తేదీ లేని మాసమై<br>ఎండమావి తిరమై ఉండలేను ఊపిరగుతూ ఇంకా నీకు దూరమై<br>ఇంకా నీకు దూరమై ఎటు పోనే నిను తలచి తలచి కళలు విడిచి ఎటు పోనే  heart touching song😢',
        textOriginal: 'తేదీ లేని మాసమై\n' +
            'ఎండమావి తిరమై ఉండలేను ఊపిరగుతూ ఇంకా నీకు దూరమై\n' +
            'ఇంకా నీకు దూరమై ఎటు పోనే నిను తలచి తలచి కళలు విడిచి ఎటు పోనే  heart touching song😢',
        updatedAt: '2022-10-11T05:18:28.000Z',
        videoId: 'Jo0D_u-QSXs',
        viewerRating: 'none'
    },
    {
        _id: ObjectId("635fec0e67862114b5a6a844"),
        authorChannelId: { value: 'UCBXZOS1k7eT0FK_55FvLGww' },
        authorChannelUrl: 'http://www.youtube.com/channel/UCBXZOS1k7eT0FK_55FvLGww',
        authorDisplayName: 'ONBEAT MANIA',
        authorProfileImageUrl: 'https://yt3.ggpht.com/81tskFemZVuTr2-4cdeGC8JvFm6-VnaqdzRh9P-fQVNQrBCilRHeSuLd39Rpg4F_-ClGuPaV=s48-c-k-c0x00ffffff-no-rj',
        canRate: true,
        likeCount: 0,
        publishedAt: '2022-10-09T09:32:00.000Z',
        textDisplay: 'Vijay 💕 yetu pone💕<br><a href="https://youtube.com/shorts/D_GXIq1SKy4?feature=share">https://youtube.com/shorts/D_GXIq1SKy4?feature=share</a>',
        textOriginal: 'Vijay 💕 yetu pone💕\n' +
            'https://youtube.com/shorts/D_GXIq1SKy4?feature=share',
        updatedAt: '2022-10-09T09:32:00.000Z',
        videoId: 'Jo0D_u-QSXs',
        viewerRating: 'none'
    },
    {
        _id: ObjectId("635fec0e67862114b5a6a845"),
        authorChannelId: { value: 'UC6YLG8xIkxFrwOPWOLXVzVw' },
        authorChannelUrl: 'http://www.youtube.com/channel/UC6YLG8xIkxFrwOPWOLXVzVw',
        authorDisplayName: 'Raju Thiti',
        authorProfileImageUrl: 'https://yt3.ggpht.com/ytc/AMLnZu_Go51_ZiD2YXkGCzIPxPsSHJJLRkGB3MNTfCsf=s48-c-k-c0x00ffffff-no-rj',
        canRate: true,
        likeCount: 0,
        publishedAt: '2022-10-04T12:13:16.000Z',
        textDisplay: 'Po ra Badacow',
        textOriginal: 'Po ra Badacow',
        updatedAt: '2022-10-04T12:13:16.000Z',
        videoId: 'Jo0D_u-QSXs',
        viewerRating: 'none'
    },
    {
        _id: ObjectId("635fec0e67862114b5a6a846"),
        authorChannelId: { value: 'UC6YLG8xIkxFrwOPWOLXVzVw' },
        authorChannelUrl: 'http://www.youtube.com/channel/UC6YLG8xIkxFrwOPWOLXVzVw',
        authorDisplayName: 'Raju Thiti',
        authorProfileImageUrl: 'https://yt3.ggpht.com/ytc/AMLnZu_Go51_ZiD2YXkGCzIPxPsSHJJLRkGB3MNTfCsf=s48-c-k-c0x00ffffff-no-rj',
        canRate: true,
        likeCount: 0,
        publishedAt: '2022-10-04T12:11:57.000Z',
        textDisplay: 'Gitu',
        textOriginal: 'Gitu',
        updatedAt: '2022-10-04T12:11:57.000Z',
        videoId: 'Jo0D_u-QSXs',
        viewerRating: 'none'
    },
    {
        _id: ObjectId("635fec0e67862114b5a6a847"),
        authorChannelId: { value: 'UCeeL92gi4-GjzuL8I4HR9yA' },
        authorChannelUrl: 'http://www.youtube.com/channel/UCeeL92gi4-GjzuL8I4HR9yA',
        authorDisplayName: 'shaik sabeer',
        authorProfileImageUrl: 'https://yt3.ggpht.com/ytc/AMLnZu_qmiD5pawYH4QG6VJhyQ_2_2Yg6i4sp4f8hA=s48-c-k-c0x00ffffff-no-rj',
        canRate: true,
        likeCount: 0,
        publishedAt: '2022-10-04T07:05:08.000Z',
        textDisplay: '💗💛💗❤️💗',
        textOriginal: '💗💛💗❤️💗',
        updatedAt: '2022-10-04T07:05:08.000Z',
        videoId: 'Jo0D_u-QSXs',
        viewerRating: 'none'
    },
    {
        _id: ObjectId("635fec0e67862114b5a6a848"),
        authorChannelId: { value: 'UCeeL92gi4-GjzuL8I4HR9yA' },
        authorChannelUrl: 'http://www.youtube.com/channel/UCeeL92gi4-GjzuL8I4HR9yA',
        authorDisplayName: 'shaik sabeer',
        authorProfileImageUrl: 'https://yt3.ggpht.com/ytc/AMLnZu_qmiD5pawYH4QG6VJhyQ_2_2Yg6i4sp4f8hA=s48-c-k-c0x00ffffff-no-rj',
        canRate: true,
        likeCount: 0,
        publishedAt: '2022-10-04T07:05:04.000Z',
        textDisplay: '🧡💗🧡💗❤️❤️💗💗💛💛❣️💗💛❣️💗💗❤️',
        textOriginal: '🧡💗🧡💗❤️❤️💗💗💛💛❣️💗💛❣️💗💗❤️',
        updatedAt: '2022-10-04T07:05:04.000Z',
        videoId: 'Jo0D_u-QSXs',
        viewerRating: 'none'
    },
    {
        _id: ObjectId("635fec0e67862114b5a6a849"),
        authorChannelId: { value: 'UC8k2LhbCfp38sQXoGhDMIng' },
        authorChannelUrl: 'http://www.youtube.com/channel/UC8k2LhbCfp38sQXoGhDMIng',
        authorDisplayName: 'Madhu Yadav',
        authorProfileImageUrl: 'https://yt3.ggpht.com/ytc/AMLnZu8brX6LNolLE-mP7wGURko0JBiO-eiKFT16Sw=s48-c-k-c0x00ffffff-no-rj',
        canRate: true,
        likeCount: 2,
        publishedAt: '2022-09-27T18:13:51.000Z',
        textDisplay: 'Emo teliyadhu ee song vinna prathi sari nalo unna ne gneypakalu ekkuvavuthune undhi ......nuvvu nannu vadhili kshnalu nimishaluga nimishalu gantaluga gantalu rojuluga,rojulu ,vaaralu,nelalu, samvacharalu ahipotunna ne gurthulu na nundi nannu vidichi petta lekunda  pothunnay, ninnu taluchukoni roju antu unte ahh roju nenu undanu emo ........itlu ee song ki..........🙏🙏',
        textOriginal: 'Emo teliyadhu ee song vinna prathi sari nalo unna ne gneypakalu ekkuvavuthune undhi ......nuvvu nannu vadhili kshnalu nimishaluga nimishalu gantaluga gantalu rojuluga,rojulu ,vaaralu,nelalu, samvacharalu ahipotunna ne gurthulu na nundi nannu vidichi petta lekunda  pothunnay, ninnu taluchukoni roju antu unte ahh roju nenu undanu emo ........itlu ee song ki..........🙏🙏',
        updatedAt: '2022-09-27T18:13:51.000Z',
        videoId: 'Jo0D_u-QSXs',
        viewerRating: 'none'
    },
    {
        _id: ObjectId("635fec0e67862114b5a6a84a"),
        authorChannelId: { value: 'UCzen2ihgl8bh0g7GGn7_ksQ' },
        authorChannelUrl: 'http://www.youtube.com/channel/UCzen2ihgl8bh0g7GGn7_ksQ',
        authorDisplayName: 'SUKAMAL PAL',
        authorProfileImageUrl: 'https://yt3.ggpht.com/YVwGrLj7wCWlGQzedu53s1fEUkSPmd55AI9Ssr0Bc_8aDFzqeTVNopXDo5MFJL6IZ6TtpZScCg=s48-c-k-c0x00ffffff-no-rj',
        canRate: true,
        likeCount: 0,
        publishedAt: '2022-09-27T05:46:14.000Z',
        textDisplay: 'KK ❤️❤️😭🙏🙏🌺🌺',
        textOriginal: 'KK ❤️❤️😭🙏🙏🌺🌺',
        updatedAt: '2022-09-27T05:46:14.000Z',
        videoId: 'Jo0D_u-QSXs',
        viewerRating: 'none'
    },
    {
        _id: ObjectId("635fec0e67862114b5a6a84b"),
        authorChannelId: { value: 'UCdv_00QatWVkfwxxDOYz1Qg' },
        authorChannelUrl: 'http://www.youtube.com/channel/UCdv_00QatWVkfwxxDOYz1Qg',
        authorDisplayName: 'Turram Surya',
        authorProfileImageUrl: 'https://yt3.ggpht.com/ytc/AMLnZu_FYRvJ2YMPj5nDzlcU3xznJN1WaXZjf247l252=s48-c-k-c0x00ffffff-no-rj',
        canRate: true,
        likeCount: 1,
        publishedAt: '2022-09-26T08:11:09.000Z',
        textDisplay: '🥰',
        textOriginal: '🥰',
        updatedAt: '2022-09-26T08:11:09.000Z',
        videoId: 'Jo0D_u-QSXs',
        viewerRating: 'none'
    },
    {
        _id: ObjectId("635fec0e67862114b5a6a84c"),
        authorChannelId: { value: 'UCh-mCoouKvO0pSHVB-eIPCQ' },
        authorChannelUrl: 'http://www.youtube.com/channel/UCh-mCoouKvO0pSHVB-eIPCQ',
        authorDisplayName: 'Lucky Gaming',
        authorProfileImageUrl: 'https://yt3.ggpht.com/BQJe9aOEoKa_U-aVTd0TggX_MP2fslzS26IKYjwhw9KZnDQuSZpYKSFyd7MpX4SCJ3Iuv1HpLNo=s48-c-k-c0x00ffffff-no-rj',
        canRate: true,
        likeCount: 1,
        publishedAt: '2022-09-25T17:28:51.000Z',
        textDisplay: '22 days  listening this song strate',
        textOriginal: '22 days  listening this song strate',
        updatedAt: '2022-09-25T17:28:51.000Z',
        videoId: 'Jo0D_u-QSXs',
        viewerRating: 'none'
    },
    {
        _id: ObjectId("635fec0e67862114b5a6a84d"),
        authorChannelId: { value: 'UCle-Bm3ep3ZSIT0uDMOGnZQ' },
        authorChannelUrl: 'http://www.youtube.com/channel/UCle-Bm3ep3ZSIT0uDMOGnZQ',
        authorDisplayName: 'Sanam World',
        authorProfileImageUrl: 'https://yt3.ggpht.com/ytc/AMLnZu86oKaOayYkX6Ec9QHk_Qp6C251QZvBp4_LIgiYG397izmXvQIIeXMiP3rPG_sN=s48-c-k-c0x00ffffff-no-rj',
        canRate: true,
        likeCount: 2,
        publishedAt: '2022-09-25T16:52:50.000Z',
        textDisplay: 'Heart Broken 💔',
        textOriginal: 'Heart Broken 💔',
        updatedAt: '2022-09-25T16:52:50.000Z',
        videoId: 'Jo0D_u-QSXs',
        viewerRating: 'none'
    },
    {
        _id: ObjectId("635fec0e67862114b5a6a84e"),
        authorChannelId: { value: 'UCgkeVtLYC8o-09eMf3Yyk_w' },
        authorChannelUrl: 'http://www.youtube.com/channel/UCgkeVtLYC8o-09eMf3Yyk_w',
        authorDisplayName: 'Devang Nanda',
        authorProfileImageUrl: 'https://yt3.ggpht.com/ytc/AMLnZu-n6KbXitHCCBif4e8HtvPbT27_IQfxi-jjYClGlEaJv4hBZQ9EUL0Y7oLxAv7U=s48-c-k-c0x00ffffff-no-rj',
        canRate: true,
        likeCount: 1,
        publishedAt: '2022-09-21T12:01:53.000Z',
        textDisplay: 'Lovely voice I&#39;m from North india...I don,t understand language...But it is fabulous really',
        textOriginal: "Lovely voice I'm from North india...I don,t understand language...But it is fabulous really",
        updatedAt: '2022-09-21T12:01:53.000Z',
        videoId: 'Jo0D_u-QSXs',
        viewerRating: 'none'
    }
]